hadoop fs -rm -R /user/root/output/outCenter1*
hadoop fs -rm -R /user/root/output/outCenter2*
hadoop fs -rm -R /user/root/output/outCenter3*
hadoop fs -rm -R /user/root/output/outCenter4*
hadoop fs -rm -R /user/root/output/outCenter5*
hadoop fs -rm -R /user/root/output/outCenter6*
hadoop fs -rm -R /user/root/output/outCenter7*
hadoop fs -rm -R /user/root/output/outCenter8*
hadoop fs -rm -R /user/root/output/outCenter9*
hadoop fs -rm -R /user/root/output/outCost*
hadoop fs -rm -R /user/root/output/dist*
